name: unittest

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Test parsers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install depends
        run: |
          pnpm install
          pnpm generate
          pnpm test

      - name: Verify grammar consistency
        run: git diff --exit-code -- */src/grammar.json
